apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: topologies.networkop.co.uk
spec:
  group: networkop.co.uk
  versions:
  - name: v1beta1
    served: true
    storage: true
  scope: Namespaced
  subresources:
    status: {}
  names:
    plural: topologies
    singular: topology
    kind: Topology
    shortNames:
    - topo
  validation:
    openAPIV3Schema:
      properties:
        status:
          properties:
            skipped:
              description: 'List of pods that are skipped by local pod'
              type: array
              items:
                type: string
                description: 'peer pod name'
            src_ip:
              description: 'Source IP of the POD'
              type: string
            net_ns:
              description: 'Network namespace of the POD'
              type: string
        spec:
          properties:
            links:
              type: array
              items:
                type: object
                description: 'A complete definition of a p2p link'
                required: ["uid", "peer_pod", "local_intf", "peer_intf"]
                properties:
                  uid:
                    description: 'Unique identified of a p2p link'
                    type: integer
                  peer_pod:
                    description: 'Name of the peer pod'
                    type: string
                  local_intf:
                    description: 'Local interface name'
                    type: string
                  peer_intf:
                    description: 'Peer interface name'
                    type: string
                  peer_ip:
                    description: '(Optional) Local IP address'
                    type: string
                  local_ip:
                    description: '(Optional) Peer IP address'
                    type: string