apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-meshnet
  namespace: kube-system
  labels:
    k8s-app: meshnet
spec:
  selector:
    matchLabels:
      name: kube-meshnet
  template:
    metadata:
      labels:
        name: kube-meshnet
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      containers:
      - name: meshnet
        securityContext:
          privileged: true
        image: docker.io/networkop/meshnet
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: cni-cfg
          mountPath: /etc/cni/net.d
        - name: cni-bin
          mountPath: /opt/cni/bin
      terminationGracePeriodSeconds: 0
      volumes:
      - name: cni-bin
        hostPath:
          path: /opt/cni/bin
      - name: cni-cfg
        hostPath:
          path: /etc/cni/net.d
