---
- name: Delete etcd cluster
  command: kubectl delete --grace-period=0 --force -f /tmp/etcd.yml
  run_once: true
  delegate_to: "{{groups['kube-master'][0]}}"

- name: Delete meshnet
  command: kubectl delete --grace-period=0 --force -f /tmp/kube-meshnet.yml
  run_once: true
  delegate_to: "{{groups['kube-master'][0]}}"


- name: Delete meshnet configuration file
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/cni/net.d/00-meshnet.conf
    - /etc/cni/net.d/meshnet.conf
    - /opt/cni/bin/meshnet
