- name: main.yml | Include prepare.yml
  include: prepare.yml
  tags:
    - always

- name: main.yml | Include install.yml
  include: install.yml
  tags:
    - install
  when: 
    - inventory_hostname == groups['kube-master'][0]
    - clean | bool == False
  delegate_to: "{{ groups['kube-master'][0] }}"
  

- name: main.yml | Include configure.yml
  include: configure.yml
  tags:
    - configure
  when: clean | bool == False

- name: main.yml | Include destroy.yml
  include: destroy.yml
  when: clean | bool == True
  ignore_errors: True
